"""One project, one ``.agora/`` directory: canvases, comment threads, sessions and the
workspace manifest stored next to the code they describe. Format: web/docs/project-storage.md.

Every write is atomic (temp file in the same directory + ``os.replace``) and versioned:
a file's version is a short sha256 of its bytes. Writers pass the version they last saw
(``base``); if the file changed in between (another tab, an editor, ``git checkout``) the
write is refused with ``Conflict`` instead of silently overwriting. ``force`` skips the
check (the user chose "keep mine"). Session logs are append-only JSONL under the same
compare-and-swap rule.

The store knows files, not the UI: it formats canvases as Excalidraw scenes, folds
session logs, and otherwise treats payloads as opaque JSON.
"""

from __future__ import annotations

import fcntl
import getpass
import hashlib
import json
import os
import re
import secrets
import subprocess
import threading
import time
import tomllib
import uuid
from collections.abc import Callable, Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Any

DIRNAME = ".agora"
FORMAT = 1
ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")
SESSION_RECORDS = ("session", "turn", "batch")

GITIGNORE = """\
# Generated by agora. Sessions and runtime files stay local; canvases, threads,
# workspace.json and config.toml are meant to be committed.
sessions/
dispatch/
run/
shares/
local/
trash/
*.tmp
*.lock
"""

CONFIG_TEMPLATE = """\
# Agora project config (commit it). Format: web/docs/project-storage.md
format = {format}

[project]
id = "{id}"
name = {name}

[server]
# Preferred port; 0 = pick a free one on every `agora up` (the live port is in run/server.json).
port = 0

[agent]
# Schema-constrained planning (the eval baseline). Sessions pick their own agent when created.
backend = "claude-cli"
model = "claude-sonnet-5"
# low | medium | high | xhigh | max; empty = the backend's default
effort = ""
"""


class Conflict(Exception):
    """The file changed since the writer's ``base`` version."""

    def __init__(self, file: str, current: str | None, base: str | None) -> None:
        super().__init__(f"{file}: expected version {base!r}, found {current!r}")
        self.file = file
        self.current = current
        self.base = base


class EmptyOverwrite(Conflict):
    """A canvas that has elements would be replaced by an empty one without the writer saying it
    is a deliberate clear (a page that lost its scene must not save that back)."""

    code = "empty-overwrite"

    def __init__(self, file: str, current: str | None) -> None:
        Exception.__init__(self, f"{file}: refusing to replace a non-empty canvas with an empty one")
        self.file = file
        self.current = current
        self.base = None


class NotEmpty(Exception):
    """An import was attempted into a project that already has data."""


class NotFound(Exception):
    """A thread operation named a thread that does not exist."""


class Locked(Exception):
    """A session's agent binding is fixed once chosen; a different one was requested."""


class NotYours(Exception):
    """A thread operation tried to edit or delete someone else's message."""


class Gone(Exception):
    """The project directory this server was started for is no longer there: it was moved,
    renamed or deleted while the server ran. Writes are refused instead of growing a new
    ``.agora/`` at the old path."""


def _session_kinds() -> tuple[str, ...]:
    from server.canvas.adapters import session_kinds

    return session_kinds()


AGENT_KINDS = _session_kinds()  # the CLIs a session can be bound to (tier T1, server/canvas/adapters/)


def version_of(data: bytes | None) -> str | None:
    return None if data is None else hashlib.sha256(data).hexdigest()[:16]


def dump_json(value: Any) -> bytes:
    """Stable, diff-friendly JSON: sorted keys, 2-space indent, trailing newline."""
    return (json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2) + "\n").encode()


def dump_line(value: Any) -> bytes:
    return (json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n").encode()


def check_id(value: str) -> str:
    if not ID_RE.match(value):
        raise ValueError(f"invalid id: {value!r}")
    return value


def to_excalidraw(scene: dict[str, Any]) -> dict[str, Any]:
    """A scene as an Excalidraw file (opens as-is on excalidraw.com). Element order is z-order; kept."""
    return {
        "type": "excalidraw",
        "version": 2,
        "source": "agora",
        "elements": [e for e in scene.get("elements") or [] if not e.get("isDeleted")],
        "appState": scene.get("appState") or {"viewBackgroundColor": "#ffffff", "gridSize": None},
        "files": scene.get("files") or {},
    }


def fold_session(lines: list[dict[str, Any]]) -> dict[str, Any]:
    """Fold a session log: the last ``session`` header, the last record per turn / batch id."""
    session: dict[str, Any] | None = None
    turns: dict[str, Any] = {}
    batches: dict[str, Any] = {}
    for rec in lines:
        t = rec.get("t")
        if t == "session":
            session = rec.get("session")
        elif t == "turn" and isinstance(rec.get("turn"), dict):
            turns[rec["turn"]["id"]] = rec["turn"]
        elif t == "batch" and rec.get("id"):
            batches[rec["id"]] = rec.get("batch")
    return {"session": session, "turns": turns, "batches": batches}


def file_error(file: str, raw: bytes, e: Exception, **extra: Any) -> dict[str, Any]:
    """What is wrong with an unreadable project file: a merge conflict (and the line of its first
    marker) or plain invalid JSON (and where the parser stopped)."""
    lines = raw.decode("utf-8", "replace").splitlines()
    marker = next((i + 1 for i, l in enumerate(lines) if l.startswith(("<<<<<<< ", "=======", ">>>>>>> ")) or l in ("<<<<<<<", ">>>>>>>")), None)
    if marker is not None:
        return {"file": file, "error": "merge-conflict", "line": marker, **extra}
    return {"file": file, "error": "invalid-json", "line": getattr(e, "lineno", None), "detail": str(e)[:200], **extra}


def participants_of(t: dict[str, Any]) -> list[dict[str, Any]]:
    seen: dict[str, dict[str, Any]] = {}
    live = [m for m in t.get("messages") or [] if not m.get("deleted")]
    for p in [t.get("createdBy"), *(m.get("by") for m in live)]:
        if isinstance(p, dict) and p.get("id") and p["id"] not in seen:
            seen[p["id"]] = p
    return list(seen.values())


def _stamp(x: dict[str, Any]) -> int:
    """When a thread or message last changed after it was written (edit, delete, restore, resolve)."""
    v = x.get("updatedAt")
    return int(v) if isinstance(v, int | float) and not isinstance(v, bool) else 0


def message_tombstone(m: dict[str, Any], at: int) -> dict[str, Any]:
    """A deleted message keeps its id, author and time (so merges don't bring it back); the text goes."""
    return {**{k: m[k] for k in ("id", "author", "at", "by") if k in m}, "text": "", "deleted": True, "updatedAt": at}


def merge_thread_files(disk: dict[str, Any], incoming: dict[str, Any]) -> dict[str, Any]:
    """Union by id. The incoming page's copy wins for fields it knows (resolved, message edits)
    unless the file's copy changed later (``updatedAt``: someone else edited or deleted it);
    threads and messages only on disk (another writer's) are kept. Deletions are tombstones
    (``deleted: true``), so they survive merges instead of coming back from an older copy.
    ``n`` collisions between two new threads are settled by renumbering the incoming one."""
    by_id = {t.get("id"): t for t in disk.get("threads") or []}
    out: list[dict[str, Any]] = []
    seen: set[Any] = set()
    for t in incoming.get("threads") or []:
        d = by_id.get(t.get("id"))
        if d is None:
            out.append(dict(t))
        else:
            win = d if _stamp(d) > _stamp(t) else t
            if win.get("deleted"):
                out.append({**win, "n": d.get("n", t.get("n"))})
            else:
                disk_msgs = {m.get("id"): m for m in d.get("messages") or []}
                mine = [disk_msgs[m.get("id")] if m.get("id") in disk_msgs and _stamp(disk_msgs[m.get("id")]) > _stamp(m) else m for m in t.get("messages") or []]
                ids = {m.get("id") for m in mine}
                extra = [m for m in d.get("messages") or [] if m.get("id") not in ids]
                msgs = sorted(mine + extra, key=lambda m: m.get("at") or 0) if extra else mine
                out.append({**win, "n": d.get("n", t.get("n")), "messages": msgs})
        seen.add(t.get("id"))
    out += [dict(t) for t in disk.get("threads") or [] if t.get("id") not in seen]
    seq = max(int(disk.get("seq") or 0), int(incoming.get("seq") or 0), max((int(t.get("n") or 0) for t in out), default=0))
    taken: set[int] = set()
    for t in out:  # disk numbering first; a clashing incoming-only thread gets the next number
        if t.get("id") in by_id:
            taken.add(int(t.get("n") or 0))
    for t in out:
        if t.get("id") not in by_id and int(t.get("n") or 0) in taken:
            seq += 1
            t["n"] = seq
        taken.add(int(t.get("n") or 0))
        t["participants"] = participants_of(t)
    return {**incoming, "seq": seq, "threads": out}


@dataclass(frozen=True)
class Person:
    id: str
    name: str

    def as_dict(self) -> dict[str, str]:
        return {"id": self.id, "name": self.name}


def local_person(cwd: Path) -> Person:
    """This machine's user: git user.name / user.email when set, else the login name."""

    def git(key: str) -> str:
        try:
            out = subprocess.run(["git", "config", key], cwd=cwd, capture_output=True, text=True, timeout=5)
            return out.stdout.strip()
        except (OSError, subprocess.SubprocessError):
            return ""

    login = getpass.getuser()
    name = git("user.name") or login
    email = git("user.email")
    return Person(id=f"mailto:{email}" if email else f"local:{login}", name=name)


class ProjectStore:
    """Read/write one project's ``.agora/``. Thread-safe; cross-process safe via a lock file."""

    def __init__(self, root: Path | str) -> None:
        self.root = Path(root).resolve()
        self.dir = self.root / DIRNAME
        self._lock = threading.RLock()
        # Called with a committed file's old bytes just before it is replaced (backup.FileHistory.keep).
        self.on_overwrite: Callable[[str, bytes], Any] | None = None
        self._ident: tuple[int, int] | None = self._identity()
        self._pid: str | None = self._project_id() if self._ident else None

    # ——— the project directory is still where it was ———
    def _identity(self) -> tuple[int, int] | None:
        try:
            st = os.stat(self.root)
        except OSError:
            return None
        return (st.st_dev, st.st_ino)

    def _project_id(self) -> str | None:
        try:
            return tomllib.loads((self.dir / "config.toml").read_text()).get("project", {}).get("id")
        except (OSError, tomllib.TOMLDecodeError):
            return None

    def gone(self) -> str | None:
        """Why this project can no longer be written (moved, renamed, deleted), or None.
        Compares the directory at ``root`` with the one the store was opened on: another inode
        means another directory. The same inode on another device is a remount (network share,
        external disk) when ``config.toml`` still names the same project. ``.agora/`` deleted
        under a running server is its own case (the project did not move)."""
        now = self._identity()
        if now is None:
            return f"项目目录 {self.root} 不在了（被移走、改名或删除）"
        if self._ident is None:
            self._ident = now
            self._pid = self._project_id()
        elif now[1] != self._ident[1]:
            return f"项目目录 {self.root} 已经换成了另一个目录（原来的被移走或改名）"
        elif now[0] != self._ident[0]:
            if self._pid is None or self._project_id() != self._pid:
                return f"项目目录 {self.root} 已经换成了另一个目录（设备变了，项目 id 也对不上）"
            self._ident = now  # remounted: same directory, same project
        if not self.dir.is_dir():
            return f"{self.dir} 被删除了（项目目录还在）：这个服务不会重建它；重新运行 `agora up`（会重建 .agora/，已提交的内容用 git 找回）"
        return None

    def check_alive(self) -> None:
        why = self.gone()
        if why:
            raise Gone(why)

    # ——— layout ———
    @property
    def run_dir(self) -> Path:
        return self.dir / "run"

    def init(self, name: str | None = None) -> bool:
        """Create ``.agora/`` if missing (idempotent). Returns True when it was created."""
        created = not (self.dir / "config.toml").exists()
        for sub in ("canvases", "threads", "sessions", "run"):
            (self.dir / sub).mkdir(parents=True, exist_ok=True)
        if self._ident is None:
            self._ident = self._identity()
        if created:
            self._atomic(
                self.dir / "config.toml",
                CONFIG_TEMPLATE.format(format=FORMAT, id=uuid.uuid4(), name=json.dumps(name or self.root.name, ensure_ascii=False)).encode(),
            )
        if not (self.dir / ".gitignore").exists():
            self._atomic(self.dir / ".gitignore", GITIGNORE.encode())
        if self._pid is None:
            self._pid = self._project_id()
        return created

    def exists(self) -> bool:
        return (self.dir / "config.toml").exists()

    def config(self) -> dict[str, Any]:
        path = self.dir / "config.toml"
        return tomllib.loads(path.read_text()) if path.exists() else {}

    def info(self) -> dict[str, Any]:
        cfg = self.config()
        proj = cfg.get("project", {})
        return {
            "id": proj.get("id") or str(self.root),
            "name": proj.get("name") or self.root.name,
            "root": str(self.root),
            "format": cfg.get("format", FORMAT),
            "config": cfg,
            "me": local_person(self.root).as_dict(),
        }

    def read_workspace_quiet(self) -> dict[str, Any] | None:
        """workspace.json, or None when it is missing or unreadable (never raises)."""
        try:
            got = self.read("workspace")
        except (OSError, ValueError):
            return None
        return got[0] if got and isinstance(got[0], dict) else None

    def is_empty(self) -> bool:
        return not (self.dir / "workspace.json").exists() and not any((self.dir / "canvases").glob("*.excalidraw"))

    # ——— files ———
    def _path(self, kind: str, id: str | None = None) -> Path:
        if kind == "workspace":
            return self.dir / "workspace.json"
        assert id is not None
        check_id(id)
        return {
            "canvas": self.dir / "canvases" / f"{id}.excalidraw",
            "threads": self.dir / "threads" / f"{id}.json",
            "session": self.dir / "sessions" / f"{id}.jsonl",
            "binding": self.dir / "sessions" / f"{id}.agent.json",
        }[kind]

    def _rel(self, path: Path) -> str:
        return str(path.relative_to(self.dir))

    @contextmanager
    def _locked(self) -> Iterator[None]:
        with self._lock:
            self.check_alive()  # never recreate .agora/ at a path the project left
            self.run_dir.mkdir(exist_ok=True)
            with open(self.run_dir / "write.lock", "a+") as fh:
                fcntl.flock(fh, fcntl.LOCK_EX)
                try:
                    yield
                finally:
                    fcntl.flock(fh, fcntl.LOCK_UN)

    @staticmethod
    def _bytes(path: Path) -> bytes | None:
        try:
            return path.read_bytes()
        except FileNotFoundError:
            return None

    @staticmethod
    def _atomic(path: Path, data: bytes) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_name(f".{path.name}.{os.getpid()}.{secrets.token_hex(4)}.tmp")
        try:
            with open(tmp, "wb") as fh:
                fh.write(data)
                fh.flush()
                os.fsync(fh.fileno())
            os.replace(tmp, path)
        finally:
            tmp.unlink(missing_ok=True)

    @staticmethod
    def _live(raw: bytes | None) -> int:
        """Elements a canvas file shows (not deleted); 0 for anything unreadable."""
        try:
            return sum(1 for e in json.loads(raw or b"{}").get("elements", []) if not e.get("isDeleted"))
        except (ValueError, AttributeError, TypeError):
            return 0

    def _keep_old(self, path: Path, current: bytes | None, shrinks: bool = False) -> None:
        """The file's previous version goes to the local history (outside the project) first.
        ``shrinks``: the write empties the canvas or drops half of it, so the version is kept
        even when the history's time gap would skip it."""
        if current is None or self.on_overwrite is None:
            return
        try:
            self.on_overwrite(self._rel(path), current, force=True) if shrinks else self.on_overwrite(self._rel(path), current)
        except OSError:
            pass  # a safety net must never block the write it protects

    def _check(self, path: Path, current: bytes | None, base: str | None, force: bool) -> None:
        if not force and version_of(current) != base:
            raise Conflict(self._rel(path), version_of(current), base)

    def read(self, kind: str, id: str | None = None) -> tuple[Any, str] | None:
        """``(data, version)`` of a JSON file (workspace / canvas / threads), or None."""
        raw = self._bytes(self._path(kind, id))
        return None if raw is None else (json.loads(raw), version_of(raw) or "")

    def write(self, kind: str, id: str | None, data: Any, *, base: str | None, force: bool = False, clear: bool = True) -> str:
        """Compare-and-swap write. ``base`` None means "I expect no file". Returns the new version.
        ``clear`` False: a canvas that has elements is not replaced by an empty one (``EmptyOverwrite``)."""
        path = self._path(kind, id)
        body = dump_json(to_excalidraw(data) if kind == "canvas" else data)
        with self._locked():
            current = self._bytes(path)
            if current == body:  # nothing changed: no write, no conflict
                return version_of(body) or ""
            self._check(path, current, base, force)
            shrinks = False
            if kind == "canvas":
                before, after = self._live(current), self._live(body)
                if before and not after and not clear:
                    raise EmptyOverwrite(self._rel(path), version_of(current))
                shrinks = before > 0 and after * 2 <= before
            self._keep_old(path, current, shrinks)
            self._atomic(path, body)
        return version_of(body) or ""

    def delete(self, kind: str, id: str | None, *, base: str | None = None, force: bool = True) -> None:
        path = self._path(kind, id)
        with self._locked():
            current = self._bytes(path)
            if current is None:
                return
            self._check(path, current, base, force)
            path.unlink()

    # ——— sessions (JSONL, append-only) ———
    def _session_lines(self, raw: bytes | None) -> list[dict[str, Any]]:
        out = []
        for line in (raw or b"").splitlines():
            if line.strip():
                try:
                    out.append(json.loads(line))
                except json.JSONDecodeError:
                    continue  # a torn last line (crash mid-append) is dropped, not fatal
        return out

    @staticmethod
    def _valid_records(records: list[Any]) -> list[dict[str, Any]]:
        for r in records:
            if not isinstance(r, dict) or r.get("t") not in SESSION_RECORDS:
                raise ValueError(f"session record must be an object with t in {SESSION_RECORDS}")
        return records

    def read_session(self, id: str) -> tuple[dict[str, Any], str] | None:
        raw = self._bytes(self._path("session", id))
        return None if raw is None else (fold_session(self._session_lines(raw)), version_of(raw) or "")

    def append_session(self, id: str, records: list[dict[str, Any]], *, base: str | None, force: bool = False) -> str:
        path = self._path("session", id)
        chunk = b"".join(dump_line(r) for r in self._valid_records(records))
        with self._locked():
            current = self._bytes(path)
            self._check(path, current, base, force)
            if not chunk:
                return version_of(current) or ""
            path.parent.mkdir(parents=True, exist_ok=True)
            with open(path, "ab") as fh:  # one write of whole lines; O_APPEND keeps it contiguous
                fh.write(chunk)
                fh.flush()
                os.fsync(fh.fileno())
            return version_of((current or b"") + chunk) or ""

    def replace_session(self, id: str, records: list[dict[str, Any]], *, base: str | None, force: bool = False) -> str:
        path = self._path("session", id)
        body = b"".join(dump_line(r) for r in self._valid_records(records))
        with self._locked():
            current = self._bytes(path)
            if current == body:
                return version_of(body) or ""
            self._check(path, current, base, force)
            self._atomic(path, body)
        return version_of(body) or ""

    # ——— agent bindings (sessions/<id>.agent.json; written only by the server) ———
    # A session is one native coding-agent session: which CLI, model and effort, chosen at
    # creation and never changed, plus the CLI's own session id (set once).
    def read_binding(self, id: str) -> dict[str, Any] | None:
        raw = self._bytes(self._path("binding", id))
        return None if raw is None else self._with_started(id, json.loads(raw))

    def bindings(self) -> dict[str, dict[str, Any]]:
        out = {}
        for p in sorted((self.dir / "sessions").glob("*.agent.json")):
            id = p.name.removesuffix(".agent.json")
            if ID_RE.match(id):
                try:
                    out[id] = self._with_started(id, json.loads(p.read_bytes()))
                except (OSError, json.JSONDecodeError):
                    continue
        return out

    def _with_started(self, id: str, b: dict[str, Any]) -> dict[str, Any]:
        """Bindings written before ``started`` existed: infer it. A session with canvas turns in its
        record or headless runs in ``run/usage`` has run; one whose record is there and shows
        neither never did (its pre-assigned id may still be created). Only when the record itself
        is missing is it taken as started (resuming a lost session must not start a new one)."""
        if "started" in b or not isinstance(b, dict):
            return b
        rec = self._path("session", id)
        try:
            raw = rec.read_bytes()
        except OSError:
            return {**b, "started": True}
        ran = bool(fold_session(self._session_lines(raw))["turns"])
        if not ran:
            try:
                ran = any(line.strip() for line in (self.run_dir / "usage" / f"{id}.jsonl").read_bytes().splitlines())
            except FileNotFoundError:
                ran = False
            except OSError:
                ran = True
        return {**b, "started": ran}

    def bind(self, id: str, *, agent: str, model: str = "", effort: str = "", native_id: str | None = None, at: int | None = None, started: bool | None = None) -> dict[str, Any]:
        """Create the binding, or confirm an identical one. A different agent/model/effort → ``Locked``."""
        if agent not in AGENT_KINDS:
            raise ValueError(f"agent must be one of {AGENT_KINDS}, got {agent!r}")
        path = self._path("binding", id)
        with self._locked():
            cur = self.read_binding(id)
            if cur is not None:
                if (cur.get("agent"), cur.get("model") or "", cur.get("effort") or "") != (agent, model or "", effort or ""):
                    raise Locked(f"session {id} is bound to {cur.get('agent')} {cur.get('model') or ''} {cur.get('effort') or ''}".strip())
                if native_id and cur.get("nativeId") and cur["nativeId"] != native_id:
                    raise Locked(f"session {id} is bound to native session {cur['nativeId']}")
                if native_id and not cur.get("nativeId"):
                    cur = {**cur, "nativeId": native_id}
                    self._atomic(path, dump_json(cur))
                return cur
            # A native id given at binding time names a session that already exists (undoing a
            # delete binds the same native session again): it counts as started unless the caller
            # knows better (the undone binding's own ``started``).
            data = {"agent": agent, "model": model or "", "effort": effort or "", "nativeId": native_id, "createdAt": at or 0, "started": bool(native_id) if started is None else bool(started)}
            if native_id:
                data["natives"] = [{"id": native_id, "at": at or 0, "reason": "bind"}]
            self._atomic(path, dump_json(data))
            return data

    def mark_started(self, id: str) -> dict[str, Any] | None:
        """The native session exists now (its log was seen, or a turn ran): from here on it is
        only ever resumed, never created again under the same id."""
        path = self._path("binding", id)
        with self._locked():
            cur = self.read_binding(id)
            if cur is None or cur.get("started") is True:
                return cur
            cur = {**cur, "started": True}
            self._atomic(path, dump_json(cur))
            return cur

    def set_native(self, id: str, native_id: str, *, reason: str = "first-run") -> dict[str, Any]:
        """Record the CLI's session id once (Claude / Pi: assigned at binding; Codex: learnt on the first run)."""
        path = self._path("binding", id)
        with self._locked():
            cur = self.read_binding(id)
            if cur is None:
                raise ValueError(f"session {id} has no agent binding")
            if cur.get("nativeId") == native_id:
                return cur
            if cur.get("nativeId"):
                raise Locked(f"session {id} is bound to native session {cur['nativeId']}")
            cur = {**cur, "nativeId": native_id, "natives": [*(cur.get("natives") or []), {"id": native_id, "at": int(time.time() * 1000), "reason": reason}]}
            self._atomic(path, dump_json(cur))
            return cur

    def rebind(self, id: str, native_id: str | None, *, reason: str, started: bool) -> dict[str, Any]:
        """Point the session at another native session — only through a recorded recovery: a fork
        (a copy continued here, a Pi log that could not be moved), or a new native session carrying
        a summary of a lost one. The old id stays in ``natives``; the agent, model and effort do not
        change. ``native_id`` None: the CLI assigns it on the next run (Codex)."""
        path = self._path("binding", id)
        with self._locked():
            cur = self.read_binding(id)
            if cur is None:
                raise ValueError(f"session {id} has no agent binding")
            natives = [*(cur.get("natives") or ([{"id": cur["nativeId"], "at": cur.get("createdAt") or 0, "reason": "bind"}] if cur.get("nativeId") else []))]
            if native_id:
                natives.append({"id": native_id, "at": int(time.time() * 1000), "reason": reason})
            cur = {k: v for k, v in cur.items() if k not in ("pendingFork", "log")}
            cur.update(nativeId=native_id, started=bool(started), natives=natives)
            self._atomic(path, dump_json(cur))
            return cur

    def set_fork(self, id: str, from_native: str, path: str | None, *, reason: str) -> dict[str, Any]:
        """The next run continues ``from_native`` as a fork (a new native id with its full history):
        Claude ``--resume … --fork-session``, Pi ``--fork <log>``, Codex ``codex fork`` (terminal)."""
        bpath = self._path("binding", id)
        with self._locked():
            cur = self.read_binding(id)
            if cur is None:
                raise ValueError(f"session {id} has no agent binding")
            cur = {**cur, "pendingFork": {"from": from_native, "path": path, "reason": reason, "at": int(time.time() * 1000)}}
            self._atomic(bpath, dump_json(cur))
            return cur

    def set_log(self, id: str, log_path: str) -> dict[str, Any] | None:
        """Remember where the native log was last found (the locator tries it first)."""
        bpath = self._path("binding", id)
        with self._locked():
            cur = self.read_binding(id)
            if cur is None or (cur.get("log") or {}).get("path") == log_path:
                return cur
            cur = {**cur, "log": {"path": log_path, "seenAt": int(time.time() * 1000)}}
            self._atomic(bpath, dump_json(cur))
            return cur

    # ——— comment threads by operation (several writers: the owner's page and share guests) ———
    # Whole-file CAS would make two people commenting at once conflict all the time. Instead the
    # server reads the latest file under the lock, applies the change and writes it back:
    # new threads and messages merge by id, ``n`` comes from the file's ``seq``.
    def merge_threads(self, id: str, incoming: dict[str, Any]) -> tuple[dict[str, Any], str, bool]:
        """Merge a page's whole threads snapshot into the file (nothing on disk is dropped).
        Returns (file, version, changed)."""
        path = self._path("threads", id)
        with self._locked():
            raw = self._bytes(path)
            disk = json.loads(raw) if raw else {"seq": 0, "threads": []}
            merged = merge_thread_files(disk, incoming)
            body = dump_json(merged)
            if body != raw:
                self._keep_old(path, raw)
                self._atomic(path, body)
        return merged, version_of(body) or "", body != raw

    def thread_op(self, id: str, op: dict[str, Any]) -> tuple[dict[str, Any], str, dict[str, Any]]:
        """Apply one ``create`` / ``reply`` / ``edit`` / ``delete`` / ``restore`` / ``resolve`` op.
        ``edit``, ``delete`` and ``restore`` act on one message and need ``actor``: the id that
        wrote it (a share guest may only change their own messages → ``NotYours``).
        Returns (file, version, the thread)."""
        path = self._path("threads", id)
        with self._locked():
            if not self._path("canvas", id).exists():
                # The canvas went to the trash (or never was): no new threads file for it.
                raise NotFound(f"canvas {id}")
            raw = self._bytes(path)
            data = json.loads(raw) if raw else {"seq": 0, "threads": []}
            threads: list[dict[str, Any]] = data.setdefault("threads", [])
            kind = op.get("op")
            now = int(op.get("at") or time.time() * 1000)
            if kind == "create":
                t = op["thread"]
                existing = next((x for x in threads if x.get("id") == t["id"]), None)
                if existing is None:
                    data["seq"] = max(int(data.get("seq") or 0), max((int(x.get("n") or 0) for x in threads), default=0)) + 1
                    t = {**t, "n": data["seq"]}
                    t["participants"] = participants_of(t)
                    threads.append(t)
                    existing = t
                thread = existing
            else:
                thread = next((x for x in threads if x.get("id") == op.get("threadId") and not x.get("deleted")), None)
                if thread is None:
                    raise NotFound(str(op.get("threadId")))
                if kind == "reply":
                    m = op["message"]
                    if not any(x.get("id") == m["id"] for x in thread["messages"]):
                        thread["messages"].append(m)
                        thread["participants"] = participants_of(thread)
                elif kind in ("edit", "delete", "restore"):
                    mid = op.get("id") or (op.get("message") or {}).get("id")
                    i = next((k for k, x in enumerate(thread["messages"]) if x.get("id") == mid), None)
                    if i is None:
                        raise NotFound(str(mid))
                    m = thread["messages"][i]
                    if not op.get("actor") or (m.get("by") or {}).get("id") != op["actor"]:
                        raise NotYours(str(mid))
                    if kind == "edit":
                        if m.get("deleted"):
                            raise NotFound(str(mid))
                        if m.get("text") != op["text"]:
                            thread["messages"][i] = {**m, "text": op["text"], "editedAt": now, "updatedAt": now}
                    elif kind == "delete":
                        if not m.get("deleted"):
                            thread["messages"][i] = message_tombstone(m, now)
                    elif m.get("deleted"):  # restore: the page that deleted it sends the text back
                        back = {**{k: m[k] for k in ("id", "author", "at", "by") if k in m}, "text": op["text"], "updatedAt": now}
                        if isinstance(op.get("editedAt"), int):
                            back["editedAt"] = op["editedAt"]
                        thread["messages"][i] = back
                    thread["participants"] = participants_of(thread)
                elif kind == "resolve":
                    thread["resolved"] = bool(op.get("resolved"))
                    thread["updatedAt"] = now
                else:
                    raise ValueError(f"unknown thread op {kind!r}")
            body = dump_json(data)
            if body != raw:
                self._keep_old(path, raw)
                self._atomic(path, body)
        return data, version_of(body) or "", thread

    # ——— whole project ———
    def _read_checked(self, kind: str, id: str | None, errors: list[dict[str, Any]]) -> tuple[Any, str] | None:
        """``read``, but a file that is not valid JSON (a git merge conflict, a bad edit) is
        reported in ``errors`` instead of failing the whole snapshot."""
        path = self._path(kind, id)
        try:
            raw = self._bytes(path)
        except OSError as e:  # no permission, an I/O error: this file is reported, the rest still loads
            errors.append({"file": self._rel(path), "error": "unreadable", "detail": e.strerror or type(e).__name__, "kind": kind, "id": id})
            return None
        if raw is None:
            return None
        try:
            return json.loads(raw), version_of(raw) or ""
        except (json.JSONDecodeError, UnicodeDecodeError) as e:
            errors.append(file_error(self._rel(path), raw, e, kind=kind, id=id, version=version_of(raw)))
            return None

    def snapshot(self) -> dict[str, Any]:
        errors: list[dict[str, Any]] = []
        ws = self._read_checked("workspace", None, errors)
        canvases: dict[str, Any] = {}
        for p in sorted((self.dir / "canvases").glob("*.excalidraw")):
            id = p.name.removesuffix(".excalidraw")
            if not ID_RE.match(id):
                continue
            got = self._read_checked("canvas", id, errors)
            if got is None:
                continue  # unreadable: listed in errors, left out (and not written) until fixed
            scene, v = got
            th = self._read_checked("threads", id, errors)
            canvases[id] = {
                "scene": scene,
                "version": v,
                "threads": None if th is None else {"data": th[0], "version": th[1]},
            }
        sessions: dict[str, Any] = {}
        for p in sorted((self.dir / "sessions").glob("*.jsonl")):
            id = p.name.removesuffix(".jsonl")
            if not ID_RE.match(id):
                continue
            try:
                folded, v = self.read_session(id) or ({}, "")
            except OSError as e:
                errors.append({"file": self._rel(p), "error": "unreadable", "detail": e.strerror or type(e).__name__, "kind": "session", "id": id})
                continue
            sessions[id] = {"state": folded, "version": v}
        bindings = self.bindings()
        return {
            **self.info(),
            "empty": self.is_empty(),
            "workspace": None if ws is None else {"data": ws[0], "version": ws[1]},
            "canvases": canvases,
            "sessions": sessions,
            "bindings": bindings,
            "errors": errors,
        }

    def import_all(self, payload: dict[str, Any]) -> None:
        """One-time import (e.g. the browser's old IndexedDB workspace) into an empty project."""
        with self._locked():
            if not self.is_empty():
                raise NotEmpty(str(self.dir))
            for id, c in (payload.get("canvases") or {}).items():
                self._atomic(self._path("canvas", id), dump_json(to_excalidraw(c.get("scene") or {})))
                if c.get("threads") is not None:
                    self._atomic(self._path("threads", id), dump_json(c["threads"]))
            for id, records in (payload.get("sessions") or {}).items():
                self._atomic(self._path("session", id), b"".join(dump_line(r) for r in self._valid_records(records)))
            if payload.get("workspace") is not None:  # last: its presence marks the project non-empty
                self._atomic(self._path("workspace"), dump_json(payload["workspace"]))
