"""One project, one ``.agora/`` directory: canvases, comment threads, sessions and the
workspace manifest stored next to the code they describe. Format: web/docs/project-storage.md.

Every write is atomic (temp file in the same directory + ``os.replace``) and versioned:
a file's version is a short sha256 of its bytes. Writers pass the version they last saw
(``base``); if the file changed in between (another tab, an editor, ``git checkout``) the
write is refused with ``Conflict`` instead of silently overwriting. ``force`` skips the
check (the user chose "keep mine"). Session logs are append-only JSONL under the same
compare-and-swap rule.

The store knows files, not the UI: it formats canvases as Excalidraw scenes, folds
session logs, and otherwise treats payloads as opaque JSON.
"""

from __future__ import annotations

import fcntl
import getpass
import hashlib
import json
import os
import re
import secrets
import subprocess
import threading
import tomllib
import uuid
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Any

DIRNAME = ".agora"
FORMAT = 1
ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")
SESSION_RECORDS = ("session", "turn", "batch")

GITIGNORE = """\
# Generated by agora. Sessions and runtime files stay local; canvases, threads,
# workspace.json and config.toml are meant to be committed.
sessions/
run/
*.tmp
*.lock
"""

CONFIG_TEMPLATE = """\
# Agora project config (commit it). Format: web/docs/project-storage.md
format = {format}

[project]
id = "{id}"
name = {name}

[server]
# Preferred port; 0 = pick a free one on every `agora up` (the live port is in run/server.json).
port = 0

[agent]
backend = "claude-cli"
model = "claude-sonnet-5"
# low | medium | high | xhigh | max; empty = the backend's default
effort = ""

[pi]
# Pi session id for this project (reserved, not used yet).
session_id = ""
"""


class Conflict(Exception):
    """The file changed since the writer's ``base`` version."""

    def __init__(self, file: str, current: str | None, base: str | None) -> None:
        super().__init__(f"{file}: expected version {base!r}, found {current!r}")
        self.file = file
        self.current = current
        self.base = base


class NotEmpty(Exception):
    """An import was attempted into a project that already has data."""


def version_of(data: bytes | None) -> str | None:
    return None if data is None else hashlib.sha256(data).hexdigest()[:16]


def dump_json(value: Any) -> bytes:
    """Stable, diff-friendly JSON: sorted keys, 2-space indent, trailing newline."""
    return (json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2) + "\n").encode()


def dump_line(value: Any) -> bytes:
    return (json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n").encode()


def check_id(value: str) -> str:
    if not ID_RE.match(value):
        raise ValueError(f"invalid id: {value!r}")
    return value


def to_excalidraw(scene: dict[str, Any]) -> dict[str, Any]:
    """A scene as an Excalidraw file (opens as-is on excalidraw.com). Element order is z-order; kept."""
    return {
        "type": "excalidraw",
        "version": 2,
        "source": "agora",
        "elements": [e for e in scene.get("elements") or [] if not e.get("isDeleted")],
        "appState": scene.get("appState") or {"viewBackgroundColor": "#ffffff", "gridSize": None},
        "files": scene.get("files") or {},
    }


def fold_session(lines: list[dict[str, Any]]) -> dict[str, Any]:
    """Fold a session log: the last ``session`` header, the last record per turn / batch id."""
    session: dict[str, Any] | None = None
    turns: dict[str, Any] = {}
    batches: dict[str, Any] = {}
    for rec in lines:
        t = rec.get("t")
        if t == "session":
            session = rec.get("session")
        elif t == "turn" and isinstance(rec.get("turn"), dict):
            turns[rec["turn"]["id"]] = rec["turn"]
        elif t == "batch" and rec.get("id"):
            batches[rec["id"]] = rec.get("batch")
    return {"session": session, "turns": turns, "batches": batches}


@dataclass(frozen=True)
class Person:
    id: str
    name: str

    def as_dict(self) -> dict[str, str]:
        return {"id": self.id, "name": self.name}


def local_person(cwd: Path) -> Person:
    """This machine's user: git user.name / user.email when set, else the login name."""

    def git(key: str) -> str:
        try:
            out = subprocess.run(["git", "config", key], cwd=cwd, capture_output=True, text=True, timeout=5)
            return out.stdout.strip()
        except (OSError, subprocess.SubprocessError):
            return ""

    login = getpass.getuser()
    name = git("user.name") or login
    email = git("user.email")
    return Person(id=f"mailto:{email}" if email else f"local:{login}", name=name)


class ProjectStore:
    """Read/write one project's ``.agora/``. Thread-safe; cross-process safe via a lock file."""

    def __init__(self, root: Path | str) -> None:
        self.root = Path(root).resolve()
        self.dir = self.root / DIRNAME
        self._lock = threading.RLock()

    # ——— layout ———
    @property
    def run_dir(self) -> Path:
        return self.dir / "run"

    def init(self, name: str | None = None) -> bool:
        """Create ``.agora/`` if missing (idempotent). Returns True when it was created."""
        created = not (self.dir / "config.toml").exists()
        for sub in ("canvases", "threads", "sessions", "run"):
            (self.dir / sub).mkdir(parents=True, exist_ok=True)
        if created:
            self._atomic(
                self.dir / "config.toml",
                CONFIG_TEMPLATE.format(format=FORMAT, id=uuid.uuid4(), name=json.dumps(name or self.root.name, ensure_ascii=False)).encode(),
            )
        if not (self.dir / ".gitignore").exists():
            self._atomic(self.dir / ".gitignore", GITIGNORE.encode())
        return created

    def exists(self) -> bool:
        return (self.dir / "config.toml").exists()

    def config(self) -> dict[str, Any]:
        path = self.dir / "config.toml"
        return tomllib.loads(path.read_text()) if path.exists() else {}

    def info(self) -> dict[str, Any]:
        cfg = self.config()
        proj = cfg.get("project", {})
        return {
            "id": proj.get("id") or str(self.root),
            "name": proj.get("name") or self.root.name,
            "root": str(self.root),
            "format": cfg.get("format", FORMAT),
            "config": cfg,
            "me": local_person(self.root).as_dict(),
        }

    def is_empty(self) -> bool:
        return not (self.dir / "workspace.json").exists() and not any((self.dir / "canvases").glob("*.excalidraw"))

    # ——— files ———
    def _path(self, kind: str, id: str | None = None) -> Path:
        if kind == "workspace":
            return self.dir / "workspace.json"
        assert id is not None
        check_id(id)
        return {
            "canvas": self.dir / "canvases" / f"{id}.excalidraw",
            "threads": self.dir / "threads" / f"{id}.json",
            "session": self.dir / "sessions" / f"{id}.jsonl",
        }[kind]

    def _rel(self, path: Path) -> str:
        return str(path.relative_to(self.dir))

    @contextmanager
    def _locked(self) -> Iterator[None]:
        with self._lock:
            self.run_dir.mkdir(parents=True, exist_ok=True)
            with open(self.run_dir / "write.lock", "a+") as fh:
                fcntl.flock(fh, fcntl.LOCK_EX)
                try:
                    yield
                finally:
                    fcntl.flock(fh, fcntl.LOCK_UN)

    @staticmethod
    def _bytes(path: Path) -> bytes | None:
        try:
            return path.read_bytes()
        except FileNotFoundError:
            return None

    @staticmethod
    def _atomic(path: Path, data: bytes) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_name(f".{path.name}.{os.getpid()}.{secrets.token_hex(4)}.tmp")
        try:
            with open(tmp, "wb") as fh:
                fh.write(data)
                fh.flush()
                os.fsync(fh.fileno())
            os.replace(tmp, path)
        finally:
            tmp.unlink(missing_ok=True)

    def _check(self, path: Path, current: bytes | None, base: str | None, force: bool) -> None:
        if not force and version_of(current) != base:
            raise Conflict(self._rel(path), version_of(current), base)

    def read(self, kind: str, id: str | None = None) -> tuple[Any, str] | None:
        """``(data, version)`` of a JSON file (workspace / canvas / threads), or None."""
        raw = self._bytes(self._path(kind, id))
        return None if raw is None else (json.loads(raw), version_of(raw) or "")

    def write(self, kind: str, id: str | None, data: Any, *, base: str | None, force: bool = False) -> str:
        """Compare-and-swap write. ``base`` None means "I expect no file". Returns the new version."""
        path = self._path(kind, id)
        body = dump_json(to_excalidraw(data) if kind == "canvas" else data)
        with self._locked():
            current = self._bytes(path)
            if current == body:  # nothing changed: no write, no conflict
                return version_of(body) or ""
            self._check(path, current, base, force)
            self._atomic(path, body)
        return version_of(body) or ""

    def delete(self, kind: str, id: str | None, *, base: str | None = None, force: bool = True) -> None:
        path = self._path(kind, id)
        with self._locked():
            current = self._bytes(path)
            if current is None:
                return
            self._check(path, current, base, force)
            path.unlink()

    # ——— sessions (JSONL, append-only) ———
    def _session_lines(self, raw: bytes | None) -> list[dict[str, Any]]:
        out = []
        for line in (raw or b"").splitlines():
            if line.strip():
                try:
                    out.append(json.loads(line))
                except json.JSONDecodeError:
                    continue  # a torn last line (crash mid-append) is dropped, not fatal
        return out

    @staticmethod
    def _valid_records(records: list[Any]) -> list[dict[str, Any]]:
        for r in records:
            if not isinstance(r, dict) or r.get("t") not in SESSION_RECORDS:
                raise ValueError(f"session record must be an object with t in {SESSION_RECORDS}")
        return records

    def read_session(self, id: str) -> tuple[dict[str, Any], str] | None:
        raw = self._bytes(self._path("session", id))
        return None if raw is None else (fold_session(self._session_lines(raw)), version_of(raw) or "")

    def append_session(self, id: str, records: list[dict[str, Any]], *, base: str | None, force: bool = False) -> str:
        path = self._path("session", id)
        chunk = b"".join(dump_line(r) for r in self._valid_records(records))
        with self._locked():
            current = self._bytes(path)
            self._check(path, current, base, force)
            if not chunk:
                return version_of(current) or ""
            path.parent.mkdir(parents=True, exist_ok=True)
            with open(path, "ab") as fh:  # one write of whole lines; O_APPEND keeps it contiguous
                fh.write(chunk)
                fh.flush()
                os.fsync(fh.fileno())
            return version_of((current or b"") + chunk) or ""

    def replace_session(self, id: str, records: list[dict[str, Any]], *, base: str | None, force: bool = False) -> str:
        path = self._path("session", id)
        body = b"".join(dump_line(r) for r in self._valid_records(records))
        with self._locked():
            current = self._bytes(path)
            if current == body:
                return version_of(body) or ""
            self._check(path, current, base, force)
            self._atomic(path, body)
        return version_of(body) or ""

    # ——— whole project ———
    def snapshot(self) -> dict[str, Any]:
        ws = self.read("workspace")
        canvases: dict[str, Any] = {}
        for p in sorted((self.dir / "canvases").glob("*.excalidraw")):
            id = p.name.removesuffix(".excalidraw")
            if not ID_RE.match(id):
                continue
            scene, v = self.read("canvas", id) or ({}, "")
            th = self.read("threads", id)
            canvases[id] = {
                "scene": scene,
                "version": v,
                "threads": None if th is None else {"data": th[0], "version": th[1]},
            }
        sessions: dict[str, Any] = {}
        for p in sorted((self.dir / "sessions").glob("*.jsonl")):
            id = p.name.removesuffix(".jsonl")
            if not ID_RE.match(id):
                continue
            folded, v = self.read_session(id) or ({}, "")
            sessions[id] = {"state": folded, "version": v}
        return {
            **self.info(),
            "empty": self.is_empty(),
            "workspace": None if ws is None else {"data": ws[0], "version": ws[1]},
            "canvases": canvases,
            "sessions": sessions,
        }

    def import_all(self, payload: dict[str, Any]) -> None:
        """One-time import (e.g. the browser's old IndexedDB workspace) into an empty project."""
        with self._locked():
            if not self.is_empty():
                raise NotEmpty(str(self.dir))
            for id, c in (payload.get("canvases") or {}).items():
                self._atomic(self._path("canvas", id), dump_json(to_excalidraw(c.get("scene") or {})))
                if c.get("threads") is not None:
                    self._atomic(self._path("threads", id), dump_json(c["threads"]))
            for id, records in (payload.get("sessions") or {}).items():
                self._atomic(self._path("session", id), b"".join(dump_line(r) for r in self._valid_records(records)))
            if payload.get("workspace") is not None:  # last: its presence marks the project non-empty
                self._atomic(self._path("workspace"), dump_json(payload["workspace"]))
